import endent from 'endent'
import glob from 'glob'
import {join} from 'path'
import copy from 'recursive-copy'
import {cache, fileSystem} from 'ros2-cache'

export async function updateCodeOwners({
  repoPath,
  codeOwnersGithubIds,
}: {
  repoPath: string
  codeOwnersGithubIds: string[]
}) {
  const files = glob.sync(join(repoPath, '**', 'CODEOWNERS'))
  const isCodeOwnersFile = files.length > 0
  if (isCodeOwnersFile) {
    throw new Error(`CODEOWNERS file already exists: ${JSON.stringify(files)}`)
  } else {
    const codeOwnersPath = join(repoPath, 'CODEOWNERS')
    const maintainersString = codeOwnersGithubIds.map((m) => `@${m}`).join(' ')
    const codeOwnersContent = endent`
      # This file was automatically generated by the maintainers-assignment-sheet
      * ${maintainersString}
    `

    fileSystem.createAndCommitFile({
      repoPath,
      filePath: codeOwnersPath,
      commitMessage: 'Add CODEOWNERS file',
      fileContent: codeOwnersContent,
    })
  }
}

async function main() {
  const outputDir = join(__dirname, '..', 'out')
  const cacheDir = join(__dirname, '..', 'cache')

  const version = 'rolling'
  const repoOrg = 'ros2'
  const repoName = 'rclcpp'
  const repoUrl = 'https://github.com/audrow/rclcpp'

  const repo = {
    maintainers: ['audrow', 'clalancette', 'wjwwood'],
  }

  // setup cache
  if (false) {
    cache.makeCacheDir({path: cacheDir, isForceRefresh: false})
    cache.makeCacheDir({path: outputDir, isForceRefresh: true})

    await cache.pullGitRepo({
      url: repoUrl,
      version: version,
      destinationPath: join(cacheDir, repoOrg, repoName),
    })
    await copy(cacheDir, outputDir, {dot: true})
  }
  const repoPath = join(outputDir, repoOrg, repoName)
  await fileSystem.resetBranch({repoPath, version: `origin/${version}`})
  await updateCodeOwners({
    repoPath,
    codeOwnersGithubIds: repo.maintainers,
  })

  // const files = glob.sync(join(repoPath, '**', 'package.xml'))
  // for (const file of files) {
  //   const packageXml = fs.readFileSync(file, 'utf8')
  //   console.log(file)
  // }
}

main()
