import endent from 'endent'
import {mkdirSync, writeFileSync} from 'fs'
import glob from 'glob'
import {dump as dumpYaml} from 'js-yaml'
import {join} from 'path'
import {cache, fileSystem} from 'ros2-cache'
import {migrateMaintainersInfo} from '../src/maintainers-info-helpers'
import {processMaintainersAssignmentSheet} from '../src/process-maintainers-assignment-sheet'

function writeYaml({data, path}: {data: unknown; path: string}) {
  const outputYaml = dumpYaml(data, {
    indent: 2,
  })
  writeFileSync(path, outputYaml)
}

async function main() {
  const isWriteFiles = false

  const dataDir = join(__dirname, '..', 'data')
  const outputDir = join(__dirname, '..', 'out')
  const cacheDir = join(__dirname, '..', 'cache')
  for (const dir of [outputDir, cacheDir]) {
    mkdirSync(dir, {recursive: true})
  }

  const oldMaintainersInfoPath = join(
    dataDir,
    '2021-09-19-maintainers-info.yaml',
  )
  const maintainersAssignmentSheetPath = join(
    dataDir,
    '2022-09-14-maintainers-assignment.csv',
  )

  const reposColumnLetter = 'a'
  const urlColumnLetter = 'b'
  const maintainersStartColumnLetter = 'o'
  const headingRowNumber = 2

  const {repos, maintainerIds: newMaintainerIds} =
    await processMaintainersAssignmentSheet({
      path: maintainersAssignmentSheetPath,
      headingRowNumber,
      maintainersStartColumnLetter,
      reposColumnLetter,
      urlColumnLetter,
    })
  const newMaintainers = migrateMaintainersInfo({
    oldMaintainersInfoPath,
    newMaintainerIds,
  })

  const version = 'rolling'
  const reposFileUrl = `https://raw.githubusercontent.com/ros2/ros2/${version}/ros2.repos`
  const reposPath = join(cacheDir, `${version}.repos.yaml`)

  cache.makeCacheDir({path: cacheDir, isForceRefresh: false})
  cache.downloadFile({path: reposPath, url: reposFileUrl})
  // const reposFileContent = reposFile.getRepos(reposPath)

  const repo = repos.repositories[0]
  const repoPath = join(cacheDir, repo.org, repo.name)
  await cache.pullGitRepo({
    url: repo.url,
    version: version,
    destinationPath: repoPath,
  })

  // const files = glob.sync(join(repoPath, '**', 'package.xml'))
  const files = glob.sync(join(repoPath, '**', 'CODEOWNERS'))
  const isCodeOwnersFile = files.length > 0
  if (!isCodeOwnersFile) {
    const codeOwnersPath = join(repoPath, 'CODEOWNERS')
    const maintainersString = repo.maintainers.map((m) => `@${m}`).join(' ')
    const codeOwnersContent = endent`
      # This file was automatically generated by the maintainers-assignment-sheet
      * ${maintainersString}
    `

    fileSystem.createAndCommitFile({
      repoPath,
      filePath: codeOwnersPath,
      commitMessage: 'Add CODEOWNERS file',
      fileContent: codeOwnersContent,
    })
  }

  if (isWriteFiles) {
    const dateString = new Date().toISOString().split('T')[0]
    writeYaml({
      data: repos,
      path: join(outputDir, `${dateString}-maintainer-assignments.yaml`),
    })
    writeYaml({
      data: newMaintainers,
      path: join(outputDir, `${dateString}-maintainers-info.yaml`),
    })
  }
}

main()
